### ISSUE TITLE
Autoresize

### ISSUE THREAD

**Issue by ramnathv** [twitter/d3kit#11]
First off, great work with this! I have a question on autoresize. While it works great out of the box, there is an annoying resize on initialization. See this gif to understand what I am talking about.

![img](http://g.recordit.co/3GPiawYIHg.gif)

Do you have any suggestions on how I can avoid this while I enable autoresize?

**Comment by kristw** [comment]
Thanks for the feedback. You can do it by either

**Choice 1. Set the initialWidth to ```'auto'```**

```
var skeleton = new d3Kit.Skeleton('#chart',
  {
    margin: {top: 60, right: 60, bottom: 60, left: 60},
    initialWidth: 'auto',
    initialHeight: 460
  }
);
```

**Choice 2. Call ```resizeToFitContainer()``` before ```autoResize()```**

```
skeleton
  .resizeToFitContainer('width')
  .autoResize('width')
```

**Comment by ramnathv** [comment]
Great! That works like a charm. You might want to update your example in the gallery, or add a note to that effect, since the flicker is annoying :)
