### ISSUE TITLE
Height sizing bug when CSS line-height not equal 0

### ISSUE THREAD

**Issue by Brideau** [twitter/d3kit#13]
I was working with a skeleton that had `autoResize` set to `both`, `resizeToFitContainer` to `full`, and no default height or width set. I noticed that the yAxis was slightly off alignment when it first loaded, and grew continuously every time the browser changed size. I logged the value of getInnerHeight() and saw that it was growing by exactly 8px each time.

It seems that this occurs whenever the line-height CSS property for the chart div isn't equal to 0. In my case, my CSS file had `html { line-height: 1.5};` so it applied to the entire page, and happened to correspond to 8px.

The bug comes from a bit of a circular logic that occurs between the size of the SVG element and the div that contains it. Basically, it happens like this:

- The SVG height is set on [line 504](https://github.com/twitter/d3kit/blob/master/dist/d3kit.js#L504) from the _totalHeight variable using `_svg.attr('height', _totalHeight);`. Let's say its 150px.
- The SVG is inserted into the chart div at [line 368](https://github.com/twitter/d3kit/blob/master/dist/d3kit.js#L368), but because of the line-height, it's 8 pixels taller at 158px.
- When the `height()` function is called on [line 494](https://github.com/twitter/d3kit/blob/master/dist/d3kit.js#L494), the `_totalHeight` variable is set to the height of the chart div, 158px, which also effects the _innerHeight property on [line 503](https://github.com/twitter/d3kit/blob/master/dist/d3kit.js#L503)
- The next time everything updates, `_svg.attr('height', _totalHeight);` is called once again, and the SVG is now set to 158px, which causes the div to be set to 166px. 
- The process then repeats itself the next time the browser resizes.

The CSS solution is pretty simple once you know what the problem is, but finding out where the bugs originates is tricky. I'm not familiar enough with your library to do a pull request, but I hope this helps!

**Comment by kristw** [comment]
Thank you so much for diagnosing the problem! We had seen this a few times, but were not able to locate root of the problems. Will do something to fix this.

**Comment by kristw** [comment]
Include the fix in latest commit. Will deploy with v3.0.0 soon. 
https://github.com/twitter/d3kit/commit/c2c7afb18d876bb2a70b531002ec3e1eb6fa9dc3

**Comment by PMudra** [comment]
Unfortunately, setting `line-height` to `0` causes IE11 to **not** display any texts anymore.
See d3kit example: https://bl.ocks.org/kristw/4628672d57f5fe822bb4c84b682abb6e
<details>
  <summary>Click see screenshot</summary>
 
![image](https://user-images.githubusercontent.com/84765/95753874-888b5500-0ca2-11eb-9d17-6aa5be58ac0f.png)

</details>

In may case I removed the `line-height` style after creating a chart:

```js
chart.chartRoot.style("line-height", null)
chart.container.style("line-height", null)
```

This works for me and I did not experience the issue as described above.
