### ISSUE TITLE
Added typescript type definition for d3Kit to DefinitelyTyped

### ISSUE THREAD

**Issue by morphatic** [twitter/d3kit#15]
Hi folks,

FYI, I just [submitted a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9680) to the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped) adding a Typescript `.d.ts` type definition file for d3Kit. Assuming it's adopted without problems, it will (eventually) be available for people wishing to use d3Kit in Typescript projects at: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/d3kit

Using [the typings CLI](https://github.com/typings/typings), one should be able to install the `d3kit.d.ts` type definition file by typing the following into your terminal:

```
$ typings install dt~d3kit --save --global
```

Thanks for putting this library out there! Hope this is useful to someone.

Cheers,
Morgan

**Comment by kristw** [comment]
Thanks!

**Comment by morphatic** [comment]
The TypeScript type definitions for d3kit have been [updated to version 3.2.0](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19952). The method for installing them has changed. To use them with d3kit in, for example, an Angular project:

```
$ npm install --save d3kit
$ npm install --save-dev @types/d3kit
```
Here is an example [project that uses d3kit with TypeScript in an Ionic app](https://github.com/morphatic/ionic-d3-demo).
