### ISSUE TITLE
Compatibility with d3 version 4 changes to dispatch

### ISSUE THREAD

**Issue by davegotz** [twitter/d3kit#16]
D3 version 4 has made changes to the way event dispatches happen.  This seems to be breaking d3-kit.

Unfortunately, D3v4 is not backward compatible.  Here is the change description for event dispatches:
https://github.com/d3/d3/blob/master/CHANGES.md#dispatches-d3-dispatch

When attempting to use d3kit with d3 version 4.1.1, the first error I get says that "_dispatch.resize is not a function" in the latest version of d3kit.js.  I get it on line 507, but the same code appears multiple times.  There are (I suspect) other changes that need to be made as well.

**Comment by kristw** [comment]
Released d3kit@2.0.0-rc1 which should resolve this. After a bit more testing will do a stable release.

**Comment by davegotz** [comment]
Thanks!  Will try to test later this week in my environment and let you know if I notice any problems.

**Comment by trebor** [comment]
we are up to rc-3: https://github.com/twitter/d3kit/releases/tag/v2.0.0-rc3. also we have tentative example updates here: http://bl.ocks.org/trebor

**Comment by kristw** [comment]
I have release version 2.0.0 and would like to close this ticket.
