### ISSUE TITLE
Add Travis CI support

### ISSUE THREAD

**Issue by caniszczyk** [twitter/d3kit#6]
Lets get a public build going!

**Comment by treboresque** [comment]
i don't appear to have admin access to the **d3kit** repo.

**Comment by caniszczyk** [comment]
@treboresque sorry about that, I enabled this for the repo now so you just need to add a .travis.yml and the build should kick off automatically

**Comment by treboresque** [comment]
done: https://github.com/twitter/d3kit/blob/master/.travis.yml

**Comment by caniszczyk** [comment]
Success, thanks! https://travis-ci.org/twitter/d3kit
